apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: waterborne
  labels:
    app: mysql
spec:
  type: ClusterIP          # Internal only — MySQL is not exposed to the internet
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
